(define (domain soldier-medic)
  (:requirements :strips :typing)
  (:types agent enemy location)
  (:predicates
    (at ?a - agent ?l - location)
    (connected ?from - location ?to - location)
    (medpack-at ?l - location)
    (health-low ?a - agent)
    (health-mid ?a - agent)
    (health-full ?a - agent)
    (enemy-at ?e - enemy ?l - location)
    (enemy-alive ?e - enemy)
  )
  (:action move
    :parameters (?a - agent ?from - location ?to - location)
    :precondition (and (at ?a ?from) (connected ?from ?to))
    :effect (and (not (at ?a ?from)) (at ?a ?to))
  )
  (:action heal-to-mid
    :parameters (?a - agent ?l - location)
    :precondition (and (at ?a ?l) (medpack-at ?l) (health-low ?a))
    :effect (and (health-mid ?a) (not (health-low ?a)) (not (medpack-at ?l)))
  )
  (:action heal-to-full
    :parameters (?a - agent ?l - location)
    :precondition (and (at ?a ?l) (medpack-at ?l) (health-mid ?a))
    :effect (and (health-full ?a) (not (health-mid ?a)) (not (medpack-at ?l)))
  )
  (:action shoot
    :parameters (?a - agent ?e - enemy ?l - location)
    :precondition (and (at ?a ?l) (enemy-at ?e ?l) (enemy-alive ?e))
    :effect (and (not (enemy-alive ?e)))
  )
)
