(define (domain crafter)
  (:requirements :strips :typing :negative-preconditions)
  (:types agent location)
  (:predicates
    (at ?a - agent ?l - location)
    (connected ?from - location ?to - location)
    (has-wood ?a - agent)
    (has-planks ?a - agent)
    (has-iron-ore ?a - agent)
    (has-iron-ingot ?a - agent)
    (has-iron-sword ?a - agent)
    (has-pickaxe ?a - agent)
    (workbench-at ?l - location)
    (furnace-at ?l - location)
    (wood-available ?l - location)
    (ore-available ?l - location)
  )
  (:action travel
    :parameters (?a - agent ?from - location ?to - location)
    :precondition (and (at ?a ?from) (connected ?from ?to))
    :effect (and (not (at ?a ?from)) (at ?a ?to))
  )
  (:action gather-wood
    :parameters (?a - agent ?l - location)
    :precondition (and (at ?a ?l) (wood-available ?l) (not (has-wood ?a)))
    :effect (and (has-wood ?a) (not (wood-available ?l)))
  )
  (:action mine-ore
    :parameters (?a - agent ?l - location)
    :precondition (and (at ?a ?l) (ore-available ?l) (has-pickaxe ?a) (not (has-iron-ore ?a)))
    :effect (and (has-iron-ore ?a) (not (ore-available ?l)))
  )
  (:action craft-planks
    :parameters (?a - agent ?l - location)
    :precondition (and (at ?a ?l) (has-wood ?a) (workbench-at ?l))
    :effect (and (has-planks ?a) (not (has-wood ?a)))
  )
  (:action build-furnace
    :parameters (?a - agent ?l - location)
    :precondition (and (at ?a ?l) (has-planks ?a) (workbench-at ?l) (not (furnace-at ?l)))
    :effect (and (furnace-at ?l) (not (has-planks ?a)))
  )
  (:action smelt-ingot
    :parameters (?a - agent ?l - location)
    :precondition (and (at ?a ?l) (has-iron-ore ?a) (furnace-at ?l))
    :effect (and (has-iron-ingot ?a) (not (has-iron-ore ?a)))
  )
  (:action forge-sword
    :parameters (?a - agent ?l - location)
    :precondition (and (at ?a ?l) (has-iron-ingot ?a) (workbench-at ?l) (furnace-at ?l))
    :effect (has-iron-sword ?a)
  )
)
