(define (domain heist)
  (:requirements :strips :typing :negative-preconditions)
  (:types agent)
  (:predicates
    (location-cased ?a - agent)
    (has-lockpicks ?a - agent)
    (disguised ?a - agent)
    (camera-disabled ?a - agent)
    (vault-unlocked ?a - agent)
    (in-vault ?a - agent)
    (safe-open ?a - agent)
    (has-jewel ?a - agent)
    (has-noise-maker ?a - agent)
    (guard-distracted ?a - agent)
    (escaped ?a - agent)
  )
  (:action case-location
    :parameters (?a - agent)
    :precondition (not (location-cased ?a))
    :effect (location-cased ?a)
  )
  (:action acquire-lockpicks
    :parameters (?a - agent)
    :precondition (not (has-lockpicks ?a))
    :effect (has-lockpicks ?a)
  )
  (:action don-disguise
    :parameters (?a - agent)
    :precondition (not (disguised ?a))
    :effect (disguised ?a)
  )
  (:action disable-camera
    :parameters (?a - agent)
    :precondition (and (location-cased ?a) (not (camera-disabled ?a)))
    :effect (camera-disabled ?a)
  )
  (:action pick-lock
    :parameters (?a - agent)
    :precondition (and (has-lockpicks ?a) (camera-disabled ?a) (not (vault-unlocked ?a)))
    :effect (vault-unlocked ?a)
  )
  (:action enter-vault
    :parameters (?a - agent)
    :precondition (and (disguised ?a) (vault-unlocked ?a) (not (in-vault ?a)))
    :effect (in-vault ?a)
  )
  (:action crack-safe
    :parameters (?a - agent)
    :precondition (and (in-vault ?a) (not (safe-open ?a)))
    :effect (safe-open ?a)
  )
  (:action steal-jewel
    :parameters (?a - agent)
    :precondition (and (in-vault ?a) (safe-open ?a) (not (has-jewel ?a)))
    :effect (has-jewel ?a)
  )
  (:action use-noise-maker
    :parameters (?a - agent)
    :precondition (and (has-noise-maker ?a) (not (guard-distracted ?a)))
    :effect (and (guard-distracted ?a) (not (has-noise-maker ?a)))
  )
  (:action exit-vault
    :parameters (?a - agent)
    :precondition (and (in-vault ?a) (guard-distracted ?a) (has-jewel ?a))
    :effect (not (in-vault ?a))
  )
  (:action escape
    :parameters (?a - agent)
    :precondition (and (not (in-vault ?a)) (has-jewel ?a))
    :effect (escaped ?a)
  )
)
